### ISSUE TITLE
Released build is missing built CSS and JS files

### ISSUE THREAD

**Issue by mattsherman** [somewherewarm/woocommerce-product-recommendations-custom-locations#9]
## Description

The released `2.0.0` version of this plugin is missing the following built CSS and JS files:

- `assets/css/admin/wc-prl-cl-admin.css`
- `assets/js/admin/wc-prl-cl-admin.js`

<img width="773" alt="Screenshot 2024-08-26 at 16 49 26" src="https://github.com/user-attachments/assets/957bb88e-da07-4399-b1d7-14e85fa94185">

This causes the those files to not load at runtime:

<img width="1276" alt="Screenshot 2024-08-26 at 16 21 30" src="https://github.com/user-attachments/assets/7a2a1a46-18c0-46a1-8dc9-a44da8efc3b2">

Which causes style issues and missing functionality:

### Current (broken)

<img width="2396" alt="Screenshot 2024-08-26 at 16 14 31" src="https://github.com/user-attachments/assets/8a933ae4-f103-4491-a393-781fd612dfeb">

- Arrows to move meta boxes are visible
- Formatting issues in **Shortcode** meta box
- **Copy shortcode** does not work (since JS did not load)

### Fixed (local branch -- once I have access I will create PR)

<img width="2396" alt="Screenshot 2024-08-26 at 16 08 00" src="https://github.com/user-attachments/assets/77e8ba9c-2763-4a54-95af-f65e0f0acbcc">

- Things look correct
- **Copy shortcode** works

## Underlying build/dev dependecies issue

I believe the underlying issue is that the build is out-of-date and not functioning correctly. At least, I could not build it on my local system. `npm i` fails due to out-of-date dependencies and missing `python2`.

<img width="1961" alt="Screenshot 2024-08-26 at 16 59 29" src="https://github.com/user-attachments/assets/4fcc2d84-ba73-4da9-b099-532c5b5e2493">

Once I updated the dev dependencies to match those in the **WooCommerce Product Recommendations** repo, I was able to successfully build the project and the styles and functionality worked at runtime. (Rather than install `python2` in an attempt to get things working, I think it is better to update the build for this project to be in-sync/up-to-date with the base plugin repo, since that is a better dev experience.)

**Comment by PanosSynetos** [comment]
cc @jimjasson
